/**
 * A portable `pg_dump` substitute for environments that do not have the Postgres
 * client tools installed (the dev box is Windows; the database lives on the VPS
 * over Tailscale).
 *
 * It writes one replayable SQL file containing, for every table in the public
 * schema: the table's CREATE statement, then INSERT statements for its rows. No
 * sequences or enum values are emitted, so a restore reproduces data and shape
 * but not identity counters -- `setval` is left to the operator.
 *
 * Usage:
 *   cd back && bun run scripts/db-backup.ts
 *   cd back && bun run scripts/db-backup.ts ./backups/pre-guest.sql
 *
 * The target file must not exist, so a mistyped path cannot silently overwrite a
 * previous backup.
 */

import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { access } from "node:fs/promises";

import postgres from "postgres";

type Column = {
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: string;
  column_default: string | null;
  ordinal_position: number;
};

const sql = postgres(process.env.DATABASE_URL ?? "", { max: 1, connect_timeout: 10 });

/** Renders a JS value as a SQL literal. */
const literal = (value: unknown): string => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "object") {
    // jsonb / json / arrays arrive already parsed by the driver.
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
};

/** Quotes an identifier only when it is not already safe. */
const ident = (name: string) =>
  /^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '""')}"`;

const tableColumns = async (table: string): Promise<Column[]> =>
  sql<Column[]>`
    SELECT column_name, data_type, udt_name, is_nullable, column_default, ordinal_position
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = ${table}
    ORDER BY ordinal_position
  `;

const run = async () => {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");

  const target = resolve(process.argv[2] ?? "./backups/db-backup.sql");

  try {
    await access(target);
    throw new Error(`refusing to overwrite an existing file: ${target}`);
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("refusing")) throw error;
    // ENOENT is the expected outcome: the file does not exist yet.
  }

  await mkdir(dirname(target), { recursive: true });

  const tables = await sql<{ tablename: string }[]>`
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public' AND tablename <> 'drizzle'
    ORDER BY tablename
  `;

  const out: string[] = [
    `-- Portable backup of the public schema`,
    `-- generated by scripts/db-backup.ts`,
    `-- tables: ${tables.length}`,
    "",
    "BEGIN;",
    "",
  ];

  for (const { tablename } of tables) {
    const columns = await tableColumns(tablename);
    if (columns.length === 0) continue;

    const names = columns.map((c) => c.column_name);

    const defs = columns.map((c) => {
      const type = c.udt_name === "USER-DEFINED" ? c.data_type : c.udt_name;
      const nullable = c.is_nullable === "YES" ? "" : " NOT NULL";
      const fallback =
        c.column_default === null
          ? type === "text" || type === "character varying"
            ? " ''"
            : ""
          : "";
      return `  ${ident(c.column_name)} ${type}${fallback}${nullable}`;
    });

    out.push(`-- ${tablename}`);
    out.push(`CREATE TABLE IF NOT EXISTS ${ident(tablename)} (`);
    out.push(defs.join(",\n"));
    out.push(");");

    // Chunked so a large table does not build one enormous statement.
    const chunkSize = 200;
    let written = 0;

    for (let offset = 0; ; offset += chunkSize) {
      const rows = await sql.unsafe(
        `SELECT ${names.map(ident).join(", ")} FROM ${ident(tablename)} LIMIT ${chunkSize} OFFSET ${offset}`,
      );

      if (rows.length === 0) break;

      for (const row of rows) {
        const values = names.map((name) => literal((row as Record<string, unknown>)[name]));
        out.push(
          `INSERT INTO ${ident(tablename)} (${names.map(ident).join(", ")}) VALUES (${values.join(", ")});`,
        );
        written += 1;
      }

      if (rows.length < chunkSize) break;
    }

    out.push(`-- ${tablename}: ${written} row(s)`);
    out.push("");
  }

  out.push("COMMIT;", "");

  await Bun.write(target, out.join("\n"));
  console.log(`backup written: ${target}`);
};

run()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(`backup failed: ${error instanceof Error ? error.message : error}`);
    process.exit(1);
  })
  .finally(() => sql.end({ timeout: 5 }));
